config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root	to:	'articles#index'
    resources :articles do
    		resources	:comments
    end

  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def tag_list
  tags.join(", ")
  end

    def	tag_list=(tags_string)
  		tag_names	=	tags_string.split(",").collect{|s|	s.strip.downcase}.uniq
  		new_or_found_tags	=	tag_names.collect	{	|name|	Tag.find_or_create_by(name:	name)	}
  		self.tags	=	new_or_found_tags
    end

  def next
    Article.where("id > ?", id).order(id: :asc).limit(1).first
  end
  def prev
    Article.where("id < ?", id).order(id: :desc).limit(1).first
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  def self.find_for_database_authentication warden_conditions
  conditions = warden_conditions.dup
  login = conditions.delete(:login)
  where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   protected

      # Attempt to find a user by it's email. If a record is found, send new
      # password instructions to it. If not user is found, returns a new user
      # with an email not found error.
      def self.send_reset_password_instructions attributes = {}
        recoverable = find_recoverable_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
        recoverable.send_reset_password_instructions if recoverable.persisted?
        recoverable
      end

      def self.find_recoverable_or_initialize_with_errors required_attributes, attributes, error = :invalid
        (case_insensitive_keys || []).each {|k| attributes[k].try(:downcase!)}

        attributes = attributes.slice(*required_attributes)
        attributes.delete_if {|_key, value| value.blank?}

        if attributes.size == required_attributes.size
          if attributes.key?(:login)
            login = attributes.delete(:login)
            record = find_record(login)
          else
            record = where(attributes).first
          end
        end

        unless record
          record = new

          required_attributes.each do |key|
            value = attributes[key]
            record.send("#{key}=", value)
            record.errors.add(key, value.present? ? error : :blank)
          end
        end
        record
      end

      def self.find_record login
        where(["username = :value OR email = :value", {value: login}]).first
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
   devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :verify_is_admin, :only => [:new, :edit, :create, :destroy]

  def index
    @articles = Article.paginate(:page => params[:page],
     :per_page => 5).order("created_at DESC")
  end

  def show
    @article	=	Article.find(params[:id])
    @comment	=	Comment.new
    @comment.article_id	=	@article.id
  end

  def new
    @article	=	Article.new
  end

  def create
    @article	=	Article.new(article_params)
		@article.save
		redirect_to	article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def	edit
		@article	=	Article.find(params[:id])
  end

  def	update
		@article	=	Article.find(params[:id])
		@article.update(article_params)
      flash.notice	=	"Article	'#{@article.title}'	Updated!"
		redirect_to	article_path(@article)
  end

  def	article_params
		params.require(:article).permit(:title,	:body, :tag_list)
  end

  private
  def verify_is_admin
  (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def	create
		@comment	=	Comment.new(comment_params)
		@comment.article_id	=	params[:article_id]
		@comment.save
		redirect_to	article_path(@comment.article)
  end
  def	comment_params
  		params.require(:comment).permit(:author_name,	:body)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :verify_is_admin, :only => [:destroy]
  def	show
		@tag	=	Tag.find(params[:id])
  end
  def index
    @tags = Tag.all
  end
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end
  private
  def verify_is_admin
  (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
		<h4><%=	comment.author_name	%>__Commented:</h4>
		<p><%=	comment.body	%></p>

</div>

app/views/articles/_form.html.erb
<div class='new-article-form'>

<%=	form_for(@article)	do	|f|	%>

      <ul>
      <%	@article.errors.full_messages.each	do	|error|	%>
          <li><%=	error	%></li>
      <%	end	%>
      </ul>

        <p>
        		<%=	f.label	:tag_list	%><br	/>
        		<%=	f.text_field	:tag_list, :class => 'entry-row'	%>
        </p>


        <p>
            <%=	f.label	:title	%><br	/>
            <%=	f.text_field	:title, :class => 'entry-row'	%>
        </p>


        <p>
            <%=	f.label	:body	%><br	/>
            <%=	f.trix_editor	:body	%>
        </p>


        <p>
            <%=	f.submit	%>
        </p>

    <%	end	%>

</div>

app/views/articles/edit.html.erb
<h1>Edit An Article </h1>

  <%=	render	partial:	'form'	%>

  <%=	link_to	"delete",	article_path(@article),	method:	:delete, data:
  {confirm:	"Really	delete	the	article?"}	%>

app/views/articles/index.html.erb
<div class="index-header">
	<h2>All	Articles</h2>
</div>

<div class="index-group">
	<ul>
		<%	@articles.each	do	|article|	%>
			<div class="index-article">
					<li>
							<h3><%=	link_to article.title, article_path(article)%></h3>

							<%= ( article.body.slice(5..165)) %>...
					</li>

					<strong>posted on:</strong> <%= article.created_at.strftime("%Y")  %>
					<strong> day_</strong>
      <%= article.created_at.strftime("%j")  %>

			</div>
		<%	end	%>
	</ul>
</div>

<%= will_paginate @posts, :class => 'paginator' %>

<% if current_user.try(:admin?) %>
<%=	link_to	"Create	a	New	Article",	new_article_path %>
<% end %>

app/views/articles/new.html.erb
<header class='new-article-header'>
  <h1>Create New Article </h1>
</header>
  <%=	render partial: 'form' %>

app/views/articles/show.html.erb
<header class="index-header">
	<div class="show-group">
		<div class="article-arrow">
			<%= link_to "Previous", @article.prev %>
		</div>
	<h1><%=	@article.title	%></h1>
		<div class="article-arrow">
			<%= link_to "next", @article.next %>
		</div>
	</div>
</header>
<div class="brand-login">
  <% if user_signed_in? %>
           <%= link_to 'Edit profile', edit_user_registration_path, :class => 'article-arrow' %> |
           <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'article-arrow'  %>
         <% else %>
           <%= link_to "Sign up", new_user_registration_path, :class => 'article-arrow' %> |
           <%= link_to "Login", new_user_session_path, :class => 'article-arrow'  %>
   <% end %>
</div>

<div class="article-body">
	<article>
		<%=	raw(@article.body)	%>
	</article>
</div>
<div class="tag-group">
  <%=link_to 'Tags', tags_path,:class => 'article-arrow spacer' %>

	<%	@article.tags.each	do	|tag|	%>
			<%=	link_to	tag.name,	tag_path(tag),:class => 'article-arrow'	%>
	<%	end	%>

</div>
<% if user_signed_in? %>
<div class="comment-section">
	<h3>Comments	(<%=	@article.comments.size	%>)</h3>
	<%=	render	partial:	'articles/comment',	collection:	@article.comments.reverse	%>
	<%=	render	partial:	'comments/form'	%>
</div>
<% else %>
<div class="comment-check">
<p>please <%= link_to "Sign up", new_user_registration_path %>
 or <%= link_to "Login", new_user_session_path %>
to comment</p>
</div>
<% end %>
<div class="article-links">
	<%=	link_to	"All Articles",	articles_path, :class => 'article-arrow'	%>
	<% if current_user.try(:admin?) %>
	<%=	link_to	"edit",	edit_article_path(@article), :class => 'article-arrow'	%>
	<% end %>
</div>

app/views/comments/_form.html.erb
<h3>Post	a	Comment</h3>
  <%=	form_for	[	@article,	@comment	]	do	|f|	%>
  		<p>
  				commenting as <%= current_user.username %><br/>
  				<%= f.hidden_field :author_name, value: current_user.username %>
  		</p>
  		<p>
  					<%=	f.text_area	:body, :style => "width:100%;"	%>
  		</p>
  		<p>
  				<%=	f.submit	'Submit'	%>
  		</p>
  <%	end	%>

app/views/layouts/_brandbar.html.erb
<div class="brand-bar">
    <h1>LosThoughts <%=	link_to	articles_path do	%>
      <i class="fas fa-home"></i></h1>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-bar">
 <a  href="https://www.facebook.com/Losthoughts-245340012672322/" target="_blank" >
   <i class="fab fa-facebook-square fa-2x"></i>
 </a>__
 <a  href="https://twitter.com/compilitrate" target="_blank" >
   <i class="fab fa-twitter-square fa-2x"></i>
 </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "LosThoughts" %></title>

    <%= stylesheet_link_tag    "application" %>

    <link href="https://fonts.googleapis.com/css?family=Amaranth" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gentium+Basic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow" rel="stylesheet">

    <%= csrf_meta_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <header class="main-header">
      <%= render partial: 'layouts/brandbar' %>
    </header>

    <%= yield %>
    <footer>
      <%= render partial: 'layouts/footer' %>
    </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tags/index.html.erb
<header class="index-header">
<h1>All Tags</h1>
</header>

<div class="tag-list">
<% @tags.each do |tag| %>
   <%= link_to tag.name, tag_path(tag), :class => 'article-arrow' %>
   <% if current_user.try(:admin?) %>
   <%= link_to "delete", tag_path(tag), method: :delete, data: {confirm: "Really delete the tag?"} %>
   <% end %>
<% end %>
</div>

app/views/tags/show.html.erb
<header class="index-header">
	<h1>Articles	Tagged	with	<%=	@tag.name	%></h1>
</header>
<ul class="tag-show">
		<%	@tag.articles.each	do	|article|	%>
				<li><%=	link_to	article.title,	article_path(article), :class => 'article-arrow'	%></li>
		<%	end	%>
</ul>